### ISSUE TITLE
Ares Addon for Course Reserves

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/librarysearch-enhance#21]
Work with Atlas Systems to recreate Ares Add On Integration to populate Course Reserves form with data from Library Search

**Comment by lisahamlett** [comment]
The initial addon is done and they are using it.

Jessica and Jenny are going to use it for a bit and then report back on what else they need it to do.  At that point, I will reach out to Atlas with an enhancement request.

**Comment by lisahamlett** [comment]
Marking it as blocked because I can't do anything until they report back, as I don't do the work.

**Comment by tclayton33** [comment]
Closing as the initial project is complete and almost all outstanding issues are resolved, out of scope, or up to Atlas. Will investigate if rows 3 and 17 on JV's spreadsheet should be tracked on the enhancement board, and if so, they will get added as new issues.
