### ISSUE TITLE
Move Sample Text links from Online resource to related resources 

### ISSUE THREAD

**Issue by SofiaSlutskaya** [emory-libraries/librarysearch-enhance#22]
Blacklight team already implemented the rule to move 856 41 Table of content to Related resources area of bib record. Can the same rule be applied to Sample text?

Sample text links are coded as 856 41 and are currently appearing as Online resource in the Library search. 
Here is an example of the 856 field 
856	41 $3 Sample text $u http://www.loc.gov/catdir/samples/cam033/2002071478.html

Please let me know if you need additional information. 

Sofia Slutskaya (sofia.slutskaya@emory.edu)

**Additional context:** Value score = 6; LibSComm patron impact score = 3

**Comment by eporter23** [comment]
@SofiaSlutskaya when we previously mapped a number of rules regarding the Related Resources field, we needed to match on exact phrases. For example, we are specifically excluding these exact phrases from being treated as "full text":

> Table of contents only
> Publisher description
> Cover image
> Contributor biographical information

Can you confirm if "Sample text" would be the exact phrase to look for, or what other variants on that phrase may be expected?

**Comment by SofiaSlutskaya** [comment]
I am not sure how github works and I am sorry if you get this e-mail multiple times.
I reviewed reports you provided awhile back for 856 41

Sample text (no punctuation after) seems to be the only option.

I hope I am answering your question.

Thank you!
_________________________________________________________
Sofia Slutskaya
Head, Resource Description
Woodruff Library | Emory University
404.727.0123 | ***@***.******@***.***>

From: eporter23 ***@***.***>
Sent: Tuesday, September 13, 2022 1:32 PM
To: emory-libraries/librarysearch-enhance ***@***.***>
Cc: Slutskaya, Sofia ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [emory-libraries/librarysearch-enhance] Move Sample Text links from Online resource to related resources (Issue #22)


@SofiaSlutskaya<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSofiaSlutskaya&data=05%7C01%7Csofia.slutskaya%40emory.edu%7Ccf0076953adf486d1f0908da95addb37%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637986871202879789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TVraMuxeswmnb6JFrWvhJZyeZNLehJiOTnKg6WyHTKs%3D&reserved=0> when we previously mapped a number of rules regarding the Related Resources field, we needed to match on exact phrases. For example, we are specifically excluding these exact phrases from being treated as "full text":

Table of contents only
Publisher description
Cover image
Contributor biographical information

Can you confirm if "Sample text" would be the exact phrase to look for, or what other variants on that phrase may be expected?

-

**Comment by tclayton33** [comment]
This is linked to [#1319](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/gh/emory-libraries/blacklight-catalog/1319) (a re-submission of this issue that includes wireframe and acceptance criteria) and [#1162](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/gh/emory-libraries/blacklight-catalog/1162) (closed issue - original implementation of these revised mappings).

**Comment by tclayton33** [comment]
Completed 3/10/23. Examples:
990005810300302486
990021968960302486
