### ISSUE TITLE
Add new vocabulary for subject headings

### ISSUE THREAD

**Issue by tclayton33** [emory-libraries/librarysearch-enhance#37]
There is a [new controlled vocabulary for Rare Materials Cataloging](https://id.loc.gov/vocabulary/rbmscv.html) that was just released as a part of id.loc.gov, and our catalogers are expected to begin using it soon. The terms in this vocabulary are especially helpful for cataloging rare books (with some that will be useful for MSS material). Please add this vocabulary to the list of vocabularies that display in Library Search. The MARC code for these terms is $2 rbmscv

According to the [Metadata and Indexing – Blacklight spreadsheet](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236), the following Solr fieldnames contain a list of specified vocabularies in their Marc mapping, and will need this vocabulary added:
subject_display_ssim
subject_ssim
subject_geo_ssim
subject_era_ssim
genre_ssim

**Acceptance criteria:**
- [9937775066302486](https://search.libraries.emory.edu/catalog/9937775066302486) - will display "Morocco bindings" in genre sections of item record and facets
- [9937164613002486](https://search.libraries.emory.edu/catalog/9937164613002486) - will display "Comedies", "Calf bindings", "Sprinkled calf bindings", and "Autographs" in genre sections of item record and facets
- [9936637789602486](https://search.libraries.emory.edu/catalog/9936637789602486) - will display "Yapp style bindings", "Ties", "Sprinkled edges", "Headbands", and "Marginalia" in genre sections of item record and facets

(Submission source - email from Elizabeth Russey Roke)

Value score = 5 ; LibSComm patron impact score = 2.14

**Comment by abelemlih** [comment]
@tclayton33 this ticket is ready for testing

**Comment by tclayton33** [comment]
@abelemlih This looks good and is ready for deployment.

**Comment by tclayton33** [comment]
deployed 10/12/23
