### ISSUE TITLE
Additional 5xx fields and subfields for display in the Library Search 

### ISSUE THREAD

**Issue by SofiaSlutskaya** [emory-libraries/librarysearch-enhance#39]
[Full details for developers](https://emory.sharepoint.com/:w:/r/sites/EmoryUniversityLibraries/Shared%20Documents/Staff/Committees%20%26%20Working%20Groups/Metadata%20Policy%20Committee/Cataloging%20and%20Authority%20Sub-Committee/Projects/Blacklight%20Catalog%20Interface/2024%205xx%20field%20enhancements_rev.docx?d=w330217660f734d059825d9babd268eea&csf=1&web=1&e=bksDUO)

Checklist
- [x] add 501; display $3 $a
- [x] add 504; display $a
- [x] add 524; display $3 $a
- [x] add 541; display $3 $c $a 
- [x] add 586; display $3 $a
- [x] add $3 to 500
- [x] add $3 to 561
- [x] add $3 to 586
- [x] add $3 to 590
- [x] add $f $u to 540

These additional fields were identified by subject librarians at Pitts and Woodruff and discussed by CATACOM. 
The fields should be located in Description/Summary area of title record display. 
In 500, 501, 524, 541, 561, 563, 586, 590 subfield 3 ($3) should be displayed at the beginning of the field and be followed by colon (:) if it is already not present in the field. 
Please display colon only if already not present in the field.

500 General note
$3 (at the beginning)
990019426520302486
500	__ |3 1876 BIBL G |a Julia Smith's signature is on the flyleaf.
500	__ |3 1876 BIBL B |a Removed and filed separately in Special Collections: Letter written by the husband of Julia E. Smith, A. J. Parker 1876 Bibl. 
(there is currently no punctuation between $3 and $a, please display colon after $3 if not present)

501 With note (Label: Bound with)
$a $3
990020860480302486 (colon should be displayed and supplied if not in the field)
|3 Pitts Theology Library copy 1 (1788 BIBL:1): |a With his: An attempt towards an improved version ... of the twelve minor prophets. London : Printed for J. Johnson [etc.], 1785.

504 Bibliography, Etc. Note;  (Label: Bibliography)
$a 
9937444689002486
Includes bibliographical references and indexes. (ending punctuation is already in bib record and should be displayed)

524 Preferred Citation of Described Materials Note (Label: Preferred Citation)
$a $3 
990006080380302486
MARC format does not prescribe any punctuation between $3 and $a. Colon should be supplied if it is not already in the field.

540 Terms Governing Use and Reproduction Note 
$f $u
9937434399002486
9937472300102486

541 Immediate Source of Acquisition Note (Label: Source of Acquisition)
$3 $c $a
990027671710302486
|3 Broadside |c Purchased |a Source unknown |e No record.
990019618500302486
990009496920302486
990010943360302486
541	0_ |c Gift; |a Cheryl Finkel; |d 2022. |3 1998 HAGG M
990010943360302486

561 Ownership and Custodial History
$3 
990019426520302486 (supply colon if possible)
|3 BIBL F |a Gift dedication inscription by Amos A. Parker, Julia Smith's husband.

586 Awards note (Display: Awards)
$a, $3 
990010014040302486
990005680270302486
586	__ |a Lambda Literary Award, 2004 (ending punctuation is not required for this field)

We probably don't have any records with $3, but we should add it to be consistent with other fields. 
Punctuation (colon) between $3 and $a is prescribed by marc formats and should be displayed.
ǂ3 Tempest fantasy: ǂa Pulitzer prize in music, 2004

590 Local note
$3 
990019426520302486
990021499730302486
|3 1876 BIBL F |a J. Michael Morgan English Bible and Psalmody Collection.
990010943360302486
590	__ |a Pitts Theology Library Haggadah Collection. |3 1998 HAGG M

**Comment by tclayton33** [comment]
@alexBLR  I'm about halfway through all our examples and think I've discovered a problem with a pattern. In this example for general note - 990032609030302486 - the 500 field with a $3 displays perfectly, but all the 500 fields without $3 no longer display. Similarly, the two examples for field 524 (Preferred Citation) also aren't displaying at all. This is one of the newly added fields, but neither example contains $3 - just $a. (990006080380302486 and 990006036980302486)

**Comment by tclayton33** [comment]
I'm attaching my testing spreadsheet so you can see what I've found so far.[5xx 7xx 8xx testing_TC20240821.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE40Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--466a535a5ace7ad3d899534d347df81a7c18cbbf/5xx%207xx%208xx%20testing_TC20240821.xlsx)

**Comment by tclayton33** [comment]
@alexBLR [5xx 7xx 8xx testing_TC20240821.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3g4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--95915d14ac1a4cc15f7506cc91baf358e6c8fb61/5xx%207xx%208xx%20testing_TC20240821.xlsx)
updated testing spreadsheet

**Comment by tclayton33** [comment]
These look good, and approved by Library Search Committee today (9/9/24)

**Comment by tclayton33** [comment]
Completed w release v1.16.3 on 11/20/24
