### ISSUE TITLE
Additional subfields in 7xx and 8xx fields for display in Library Search

### ISSUE THREAD

**Issue by SofiaSlutskaya** [emory-libraries/librarysearch-enhance#40]
[Full details for developers](https://emory.sharepoint.com/:w:/r/sites/EmoryUniversityLibraries/Shared%20Documents/Staff/Committees%20%26%20Working%20Groups/Metadata%20Policy%20Committee/Cataloging%20and%20Authority%20Sub-Committee/Projects/Blacklight%20Catalog%20Interface/2024%207xx%20and%208xx%20field%20enhancement.docx?d=w8c4c37e0bcbf4bc8acf4fbabcb314cc5&csf=1&web=1&e=0bcsmA)

Checklist:
- [ ] add $3 to 700
- [ ] add $3 to 710
- [ ] add $3 to 711
- [ ] add $3 to 800
- [ ] add $3 to 810
- [ ] add $3 to 811

These additional sub-fields were identified by subject librarians at Pitts and discussed by CATACOM. 
$3 should be displayed at the beginning of the field. Colon should be supplied after $3 if it is not already in the record. 

700 $3
990013759890302486
700	1_ |3 Pitts Theology Library copy |a Scharff, Fritz, |d -1991, |e former owner.
990012488000302486
700	1_ |3 Pitts Theology Library copy: |a Scharff, Fritz, |d -1991, |e former owner

710 $3 there are currently no records with $3 in the catalog, but it is the same use as 700$3 and should be implemented 
711 $3 there are currently no records with $3 in the catalog, but it is the same use as 700$3 and should be implemented 

800 $3
990036117230302486
800	1_ |3 Pitts Theology Library copy 2: |a Wright, N. T. |q (Nicholas Thomas). |t For everyone Bible study guides.

810 $3
990012413680302486
810	2_ |3 Pitts Theology Library copy3 |a Pitts Theology Library |t J. Michael Morgan English Bible and Psalmody Collection.

990010834900302486
810	2_ |3 Pitts Theology Library copy 2 (1719 BIBL E): |a Pitts Theology Library. |t J. Michael Morgan English Bible and Psalmody Collection.

811 $3 there are currently no records with $3 in the catalog, but it is the same use as 800 $3 and should be implemented

**Comment by tclayton33** [comment]
@alexBLR Attaching my testing document. So far I'm not seeing the same issue w/ 7xx and 8xx we saw with the 5xx. (the fields are still displaying, with or without the presence of $3). I am seeing two other issues: 
-the linking issue you know about - the $3 should not be part of the hyperlink
-with 800, MMSID 990036117230302486 - the $0 subfields are now also displaying, which we don't want. So far, I only have the one example for all of the 8xx fields, but I'll look for more.
[5xx 7xx 8xx testing_TC20240821.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTU4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c701c9608c45d62c61f010e426df7f0a76d115c/5xx%207xx%208xx%20testing_TC20240821.xlsx)

**Comment by tclayton33** [comment]
These look good, and approved by Library Search Committee today (9/9/24)

**Comment by tclayton33** [comment]
Completed w release v1.16.3 on 11/20/24
