### ISSUE TITLE
Update Library Search tagline

### ISSUE THREAD

**Issue by tclayton33** [emory-libraries/librarysearch-enhance#42]
Fall 2023 UX research revealed that our tagline used to describe Library Search on the [homepage](https://search.libraries.emory.edu/) is misleading. Users aren't clear on what type of content is meant by the word journals. Please change the tagline so that it reads: Search books, e-books, journal and newspaper titles, videos and more. [Currently it says: Search books, e-books, journals, videos and more].

<img width="723" alt="updatedTagline" src="https://github.com/emory-libraries/librarysearch-enhance/assets/115043483/a88a299e-10c5-46d4-80bb-1afdafbd180d">

**Comment by tclayton33** [comment]
This ticket was adjusted based on discussion in the Q2 prioritization meeting. Original intent was to implement this first on the features dashboard to validate with user testing. When looking at overall capacity for the Q2 sprint, we removed this requirement to reduce capacity.

**Comment by CB987** [comment]
[PR#1405](https://github.com/emory-libraries/blacklight-catalog/pull/1405)

**Comment by CB987** [comment]
<img width="988" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWczQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c93a656147215cedbbe554aab0b8563b0d846496/Screenshot%202024-04-04%20at%203.54.55%E2%80%AFPM.png" alt="Screenshot 2024-04-04 at 3.54.55 PM.png" />
<img width="988" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWszQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac3c25693091c2518e1a5c73854afa64e8bc7bc5/Screenshot%202024-04-04%20at%203.54.55%E2%80%AFPM.png" alt="Screenshot 2024-04-04 at 3.54.55 PM.png" />

**Comment by tclayton33** [comment]
@CB987 I'm good with reducing the size to whatever you think looks good.

**Comment by CB987** [comment]
<img width="1238" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW80QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c17be0e9e0c299496f258f698c777a2059f3a38/Screenshot%202024-04-04%20at%206.16.33%E2%80%AFPM.png" alt="Screenshot 2024-04-04 at 6.16.33 PM.png" />

**Comment by tclayton33** [comment]
@CB987 I think we need to decrease the font on this even more (Library Search Committee is in agreement). At the size I normally view my browser the "more" was still wrapping to the next line. [It isn't visible now, but this was temporarily visible on Test last week when Ayoub was testing one of the solutions to the advanced search issue.]

**Comment by CB987** [comment]
Thanks! I will get that done.

**Comment by tclayton33** [comment]
looks good; ready for production @abelemlih

**Comment by abelemlih** [comment]
@tclayton33 this ticket was deployed to production (v1.13.0). It is ready to close.
