### ISSUE TITLE
Features dashboard: Open the Access facet by default

### ISSUE THREAD

**Issue by tclayton33** [emory-libraries/librarysearch-enhance#43]
As a result of Fall 2023 usability testing, MarketAde suggested opening the access facet by default in order to clarify its meaning for users. We would like to confirm this is effective with testing. Please implement this functionality in a test environment (perhaps the admin features toggle). 

**Requirement:** when a user executes a search, the Access facet is open automatically on the results page.
<img width="516" alt="open Access facet" src="https://github.com/emory-libraries/librarysearch-enhance/assets/115043483/88c46b1e-b70b-4c2a-9104-18bd0c60915a">

(We may also want to consider effectiveness and desirability of opening the facet by default on the start page.)

**Comment by CB987** [comment]
<img width="509" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzB4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97117c7692fe3721a0c304352d7a8955b6b31d2f/Screenshot%202024-06-03%20at%204.16.06%E2%80%AFPM.png" alt="Screenshot 2024-06-03 at 4.16.06 PM.png" />
https://github.com/emory-libraries/blacklight-catalog/tree/43-access-facet
@abelemlih is going to look over this and, if it is ready, add the feature flipper part

**Comment by abelemlih** [comment]
Feature is approved and merged, refer to this PR: https://github.com/emory-libraries/blacklight-catalog/pull/1418

The feature is also behind a feature toggle accessible through the admin dashboard, refer to the screenshot below:

<img width="1710" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVZKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a59a654e1f4826fb36ae068d4a686c0ac1a7c56a/Screenshot%202024-06-07%20at%202.41.55%E2%80%AFPM.png" alt="Screenshot 2024-06-07 at 2.41.55 PM.png" />

**Comment by tclayton33** [comment]
Looks good @CB987 and @abelemlih. This one is also approved for production.

**Comment by abelemlih** [comment]
@tclayton33 this ticket was deployed to production (v1.13.0). It is ready to close.
