### ISSUE TITLE
Change "Resource Type" label to "Format"

### ISSUE THREAD

**Issue by tclayton33** [emory-libraries/librarysearch-enhance#44]
One recommendation that came out of Fall 2023 usability testing was to consider switching our Resource Type label to Format, and we would like to implement this change. This label needs to be adjusted in 3 places:

Requirements: change **Resource Type** to **Format** in these locations:
- facet label (1)
- on the results list (2)
- on the item record (3)

![FormatChangesResultsPage](https://github.com/emory-libraries/librarysearch-enhance/assets/115043483/b420e587-a002-4b30-82f9-125c2aee616e)
![FormatChangeItemRecord](https://github.com/emory-libraries/librarysearch-enhance/assets/115043483/93b68c41-18f9-4b33-992b-23460c9d736d)

**Comment by tclayton33** [comment]
This ticket was adjusted based on discussion in the Q2 prioritization meeting. Original intent was to implement this first on the features dashboard to validate with user testing. When looking at overall capacity for the Q2 sprint, we removed this requirement to reduce capacity.

**Comment by CB987** [comment]
<img width="297" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWc4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8fa7f93fe8d332d4725a23040e17f55c97a40a43/Screenshot%202024-04-05%20at%203.21.43%E2%80%AFPM.png" alt="Screenshot 2024-04-05 at 3.21.43 PM.png" />

**Comment by CB987** [comment]
[PR #1406](https://github.com/emory-libraries/blacklight-catalog/pull/1406)

**Comment by tclayton33** [comment]
looks good; ready for production @abelemlih

**Comment by abelemlih** [comment]
@tclayton33 this ticket was deployed to production (v1.13.0). It is ready to close.
